import type {
  Lead,
  DashboardMetrics,
  WhatsAppQueueItem,
  FollowUp,
  Activity,
  OutreachMetric,
  TemplatePerformance,
} from './types'

// Mock Leads Data
export const mockLeads: Lead[] = [
  {
    id: 'lead_001',
    company_name: 'TechStart Solutions',
    status: 'new',
    employees: 65,
    city: 'Mohali',
    industry: 'SaaS',
    linkedin_url: 'https://linkedin.com/company/techstart',
    phone: '+91 98765 43210',
    whatsapp_number: '919876543210',
    whatsapp_status: 'pending',
    created_at: '2026-09-15T10:30:00Z',
    updated_at: '2026-09-15T10:30:00Z',
  },
  {
    id: 'lead_002',
    company_name: 'InnovateTech Pvt Ltd',
    status: 'contacted',
    employees: 92,
    city: 'Chandigarh',
    industry: 'IT Services',
    linkedin_url: 'https://linkedin.com/company/innovatetech',
    phone: '+91 98765 43211',
    whatsapp_number: '919876543211',
    whatsapp_status: 'sent',
    created_at: '2026-09-14T15:20:00Z',
    updated_at: '2026-09-15T09:15:00Z',
  },
  {
    id: 'lead_003',
    company_name: 'CloudFirst Systems',
    status: 'responded',
    employees: 120,
    city: 'Panchkula',
    industry: 'Cloud Services',
    linkedin_url: 'https://linkedin.com/company/cloudfirst',
    phone: '+91 98765 43212',
    whatsapp_number: '919876543212',
    whatsapp_status: 'sent',
    created_at: '2026-09-13T12:00:00Z',
    updated_at: '2026-09-15T08:30:00Z',
  },
  {
    id: 'lead_004',
    company_name: 'DataDriven Analytics',
    status: 'qualified',
    employees: 78,
    city: 'Mohali',
    industry: 'Analytics',
    linkedin_url: 'https://linkedin.com/company/datadriven',
    phone: '+91 98765 43213',
    whatsapp_number: '919876543213',
    whatsapp_status: 'sent',
    created_at: '2026-09-12T09:45:00Z',
    updated_at: '2026-09-15T11:00:00Z',
  },
  {
    id: 'lead_005',
    company_name: 'FinTech Pro Solutions',
    status: 'new',
    employees: 45,
    city: 'Chandigarh',
    industry: 'FinTech',
    linkedin_url: 'https://linkedin.com/company/fintechpro',
    phone: '+91 98765 43214',
    whatsapp_number: '919876543214',
    whatsapp_status: 'pending',
    created_at: '2026-09-15T08:00:00Z',
    updated_at: '2026-09-15T08:00:00Z',
  },
  {
    id: 'lead_006',
    company_name: 'EduLearn Technologies',
    status: 'contacted',
    employees: 110,
    city: 'Panchkula',
    industry: 'EdTech',
    linkedin_url: 'https://linkedin.com/company/edulearn',
    phone: '+91 98765 43215',
    whatsapp_number: '919876543215',
    whatsapp_status: 'opened',
    created_at: '2026-09-14T14:30:00Z',
    updated_at: '2026-09-15T10:20:00Z',
  },
  {
    id: 'lead_007',
    company_name: 'HealthTech Innovations',
    status: 'won',
    employees: 85,
    city: 'Mohali',
    industry: 'HealthTech',
    linkedin_url: 'https://linkedin.com/company/healthtechinnovations',
    phone: '+91 98765 43216',
    whatsapp_number: '919876543216',
    whatsapp_status: 'sent',
    created_at: '2026-09-10T11:00:00Z',
    updated_at: '2026-09-14T16:45:00Z',
  },
  {
    id: 'lead_008',
    company_name: 'RetailSmart Pvt Ltd',
    status: 'new',
    employees: 55,
    city: 'Chandigarh',
    industry: 'E-commerce',
    linkedin_url: 'https://linkedin.com/company/retailsmart',
    phone: '+91 98765 43217',
    whatsapp_number: '919876543217',
    whatsapp_status: 'pending',
    created_at: '2026-09-15T07:15:00Z',
    updated_at: '2026-09-15T07:15:00Z',
  },
]

// Mock Dashboard Metrics
export const mockMetrics: DashboardMetrics = {
  emails_sent_today: 47,
  whatsapp_queue_count: 23,
  followups_due_today: 12,
  replies_today: 8,
  pipeline: {
    new: 156,
    contacted: 89,
    responded: 24,
    qualified: 15,
    won: 7,
  },
  last_sync: new Date().toISOString(),
}

// Mock WhatsApp Queue
export const mockWhatsAppQueue: WhatsAppQueueItem[] = [
  {
    lead_id: 'lead_001',
    company_name: 'TechStart Solutions',
    employees: 65,
    city: 'Mohali',
    industry: 'SaaS',
    template: 'Initial outreach',
    whatsapp_url: 'https://wa.me/919876543210?text=Hello%20TechStart',
    status: 'READY',
    priority_score: 95,
  },
  {
    lead_id: 'lead_005',
    company_name: 'FinTech Pro Solutions',
    employees: 45,
    city: 'Chandigarh',
    industry: 'FinTech',
    template: 'Follow-up day 3',
    whatsapp_url: 'https://wa.me/919876543214?text=Hello%20FinTech',
    status: 'READY',
    priority_score: 88,
  },
  {
    lead_id: 'lead_008',
    company_name: 'RetailSmart Pvt Ltd',
    employees: 55,
    city: 'Chandigarh',
    industry: 'E-commerce',
    template: 'Initial outreach',
    whatsapp_url: 'https://wa.me/919876543217?text=Hello%20RetailSmart',
    status: 'READY',
    priority_score: 82,
  },
]

// Mock Follow-ups
export const mockFollowUps: FollowUp[] = [
  {
    id: 'followup_001',
    lead_id: 'lead_002',
    company_name: 'InnovateTech Pvt Ltd',
    due_date: new Date().toISOString(),
    status: 'pending',
    notes: 'Follow up on demo request',
    created_at: '2026-09-14T16:00:00Z',
  },
  {
    id: 'followup_002',
    lead_id: 'lead_003',
    company_name: 'CloudFirst Systems',
    due_date: new Date(Date.now() - 86400000).toISOString(), // Yesterday
    status: 'overdue',
    notes: 'Send pricing proposal',
    created_at: '2026-09-13T14:30:00Z',
  },
  {
    id: 'followup_003',
    lead_id: 'lead_006',
    company_name: 'EduLearn Technologies',
    due_date: new Date().toISOString(),
    status: 'pending',
    notes: 'Schedule call with CEO',
    created_at: '2026-09-14T11:00:00Z',
  },
  {
    id: 'followup_004',
    lead_id: 'lead_004',
    company_name: 'DataDriven Analytics',
    due_date: new Date(Date.now() + 86400000).toISOString(), // Tomorrow
    status: 'pending',
    notes: 'Technical discussion',
    created_at: '2026-09-15T10:00:00Z',
  },
]

// Mock Activities
export const mockActivities: Activity[] = [
  {
    id: 'activity_001',
    type: 'whatsapp_sent',
    lead_id: 'lead_002',
    company_name: 'InnovateTech Pvt Ltd',
    timestamp: new Date().toISOString(),
    details: 'Initial outreach message sent',
  },
  {
    id: 'activity_002',
    type: 'email_sent',
    lead_id: 'lead_003',
    company_name: 'CloudFirst Systems',
    timestamp: new Date(Date.now() - 3600000).toISOString(),
    details: 'Proposal email sent',
  },
  {
    id: 'activity_003',
    type: 'lead_created',
    lead_id: 'lead_008',
    company_name: 'RetailSmart Pvt Ltd',
    timestamp: new Date(Date.now() - 7200000).toISOString(),
    details: 'New lead from website',
  },
  {
    id: 'activity_004',
    type: 'follow_up_created',
    lead_id: 'lead_002',
    company_name: 'InnovateTech Pvt Ltd',
    timestamp: new Date(Date.now() - 10800000).toISOString(),
    details: 'Demo follow-up scheduled',
  },
  {
    id: 'activity_005',
    type: 'whatsapp_opened',
    lead_id: 'lead_006',
    company_name: 'EduLearn Technologies',
    timestamp: new Date(Date.now() - 14400000).toISOString(),
  },
  {
    id: 'activity_006',
    type: 'email_sent',
    lead_id: 'lead_005',
    company_name: 'FinTech Pro Solutions',
    timestamp: new Date(Date.now() - 18000000).toISOString(),
    details: 'Introduction email',
  },
]

// Mock Outreach Metrics
export const mockOutreachMetrics: OutreachMetric[] = [
  { date: '2026-09-09', emails_sent: 32, whatsapp_sent: 28, responses: 6 },
  { date: '2026-09-10', emails_sent: 45, whatsapp_sent: 35, responses: 8 },
  { date: '2026-09-11', emails_sent: 38, whatsapp_sent: 42, responses: 9 },
  { date: '2026-09-12', emails_sent: 52, whatsapp_sent: 31, responses: 11 },
  { date: '2026-09-13', emails_sent: 41, whatsapp_sent: 38, responses: 7 },
  { date: '2026-09-14', emails_sent: 48, whatsapp_sent: 44, responses: 10 },
  { date: '2026-09-15', emails_sent: 47, whatsapp_sent: 39, responses: 8 },
]

// Mock Template Performance
export const mockTemplatePerformance: TemplatePerformance[] = [
  {
    template_name: 'Initial outreach',
    sent_count: 145,
    response_count: 32,
    response_rate: 22.1,
  },
  {
    template_name: 'Follow-up day 3',
    sent_count: 98,
    response_count: 18,
    response_rate: 18.4,
  },
  {
    template_name: 'Demo request',
    sent_count: 67,
    response_count: 22,
    response_rate: 32.8,
  },
  {
    template_name: 'Proposal follow-up',
    sent_count: 54,
    response_count: 12,
    response_rate: 22.2,
  },
  {
    template_name: 'Meeting reminder',
    sent_count: 38,
    response_count: 15,
    response_rate: 39.5,
  },
]
